### Login Fail

POST {{host}}/v1/session
Content-Type: application/json

{
  "username": "this_is_username",
  "password": "b"
}

### Login Pass

POST {{host}}/v1/session
Content-Type: application/json

{
  "username": "this_is_username",
  "password": "this_is_password"
}

> {%
    client.global.set("token", response.body.ID);
%}

### GetProcesses

GET {{host}}/v1/processes
Token: {{token}}

### DeleteProcess (a.k.a kill by PID)

# Find the proper UID through launch one and GetProcesses or ps.
DELETE {{host}}/v1/processes/186451
Token: {{token}}

### GetApplications

GET {{host}}/v1/applications
Token: {{token}}