### Login Fail

POST {{host}}/v1/session
Content-Type: application/json

{
  "username": "this_is_username",
  "password": "b"
}

### Login Pass

POST {{host}}/v1/session
Content-Type: application/json

{
  "username": "this_is_username",
  "password": "this_is_password"
}

> {%
    client.global.set("token", response.body.ID);
%}

### GetApplications

GET {{host}}/v1/applications
Token: {{token}}

### DeleteApplication (a.k.a kill by PID)

DELETE {{host}}/v1/applications/186451
Token: {{token}}