### CORS

OPTIONS {{host}}/v1/what-ever-path


### Login

POST {{host}}/v1/session
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("token", response.body.ID);
%}

### GetProcesses

GET {{host}}/v1/processes
Token: {{token}}

### DeleteProcess (a.k.a kill by PID)

# Find the proper UID through launch one and GetProcesses or ps.
DELETE {{host}}/v1/processes/186451
Token: {{token}}

### GetApplications

GET {{host}}/v1/applications
Token: {{token}}

### StartApplication

PUT {{host}}/v1/applications/{{appid}}/instances
Token: {{token}}

### ReloadAppConfig

PUT {{host}}/v1/dashboard/app-config/reload
Token: {{token}}

### GetApplicationOutput

GET {{host}}/v1/applications/{{appid}}/output
Token: {{token}}